version: 0.2

env:
  variables:
     ARTIFACTORY_URL: "https://alexatwoodside.jfrog.io/alexatwoodside"
  parameter-store:
     JFROG_API_KEY: "alex-jfrog-trial-apikey" #pragma: allowlist secret

phases:
  pre_build:
    commands:
      - yum install jq -y
  build:
    commands:
      - ls
      - jfrog rt c --url $ARTIFACTORY_URL --apikey $JFROG_API_KEY
      - jfrog rt ping
      - version=$(cat package.json | jq '.version' --raw-output)
      - echo $version