version: 0.2

env:
  variables:
     ARTIFACTORY_URL: "https://alexatwoodside.jfrog.io/alexatwoodside/"
  parameter-store:
     JFROG_API_KEY: "alex-jfrog-trial-apikey" #pragma: allowlist secret

phases:
  pre_build:
    commands:
      - apk update
      - apk add nodejs-npm
      - apk add jq
  build:
    commands:
      - ls
      # - jfrog rt c --url $ARTIFACTORY_URL --apikey $JFROG_API_KEY
      # - jfrog rt ping
      - version=$(cat package.json | jq '.version' --raw-output)
      - project_name=$(cat package.json | jq '.name' --raw-output)
      - jfrog rt npmi mynpm-registry --build-name=$project_name --build-number=$version --url $ARTIFACTORY_URL --apikey $JFROG_API_KEY
      - jfrog rt bp $project_name $version