---
- name: adding the nodesource apt key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
 
- name: adding nodesource repository
  apt_repository: repo='deb https://deb.nodesource.com/node_{{ nodejs_version }} trusty main' state=present
 
- name: installing git and nodejs
  apt: name={{ item }} update_cache=yes state=present
  with_items:
      - git-core
      - nodejs

- name: downloading the dvna from github
  git: repo=https://github.com/quantumfoam/dvna.git dest=/home/vagrant/dvna

- name: install pm2
  npm: name=pm2 global=yes

- name: installing the npm packages for dvna
  npm: path=/home/vagrant/dvna

- name: pm2 as startup
  command: pm2 startup

- name: stop dvna
  command: pm2 stop dvna chdir=/home/vagrant/dvna
  ignore_errors: yes

- name: start dvna
  command: pm2 start dvna.js --name dvna chdir=/home/vagrant/dvna
  ignore_errors: yes
